services:
  nginx:
    build:
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
        NGINX_RUNTIME_SNIPPETS: 1
        NGINX_SNIPPET_SOURCE: ./include.d
    volumes:
      - ./ssl:/etc/ssl/nginx
      - ./include.d:/etc/nginx/include.d
    ports:
      - 1080:1080
      - 1443:1443
      - 1465:1465
      - 1995:1995
