services:
  smtp:
    build:
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/tcp_server:latest
      target: smtp
      args:
        hostname: localhost
    volumes:
      - ./email:/mnt/email_data:Z
    ports:
      - 1465:465
