services:
  nginx:
    build:
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
    volumes:
      - ./ssl:/etc/ssl/nginx
    ports:
      - 1080:1080
      - 1443:1443
