services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
        NGINX_RUNTIME_SNIPPETS: 1
    security_opt:
      - label:disable
    volumes:
      - ./ssl:/etc/ssl/nginx:ro
      - ./nginx_snippets:/etc/nginx/include.d:ro
    ports:
      - 1080:1080
      - 1443:1443
      - 1465:1465
      - 1995:1995
