services:
  nginx:
    build:
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
    volumes:
      - ./ssl:/etc/ssl/nginx
    ports:
      - 1080:1080
      - 1443:1443
      - 1465:1465
      - 1995:1995
