services:
  tcp_server:
    build:
      context: https://github.com/underground-software/tcp_server.git#fcb6840503f088b657ab75a6090f6bc6f514f77d
      target: tcp_server
  pop:
    build:
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/pop_tcp_server:latest
      target: pop
    volumes:
      - ./email:/mnt/mail:Z
    ports:
      - 995:995
