services:
  nginx:
    build:
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_SNIPPET_SOURCE: ./include.d
    volumes:
      - ./ssl:/etc/ssl/nginx:Z
    ports:
      - 80:80
      - 443:443
      - 465:465
      - 995:995
