services:
  pop:
    build:
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/tcp_server:latest
      target: pop
    security-opt:
      - label:disable
    volumes:
      - ./email:/mnt/mail
    ports:
      - 1995:995
