services:
  nginx:
    build:
      dockerfile: Containerfile
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./include.d/
      target: nginx
    volumes:
      - ./ssl:/etc/ssl/nginx:Z
    ports:
      - 80:80
      - 443:443
      - 465:465
      - 995:995
